Update pipeline

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -19,7 +19,7 @@ jobs:
       - name: Gradlew Check
         run: | 
            chmod +x ./gradlew
-           ./gradlew --no-daemon check
+           ./gradlew check
       - name: Codecov coverage report upload
         uses: codecov/codecov-action@v2.1.0 
         with:
@@ -31,13 +31,15 @@ jobs:
             snyk auth ${{secrets.SNYK_TOKEN}}
             snyk monitor
       - name: Build Jar
-        run: ./gradlew --no-daemon bootJar
+        run: ./gradlew bootJar
       - name: Publish Jar
         uses: actions/upload-artifact@v2.2.4
         with: 
           path: ./build/libs/*.jar
+      - name: Rename Jar
+        run: mv ./build/libs/$(ls ./build/libs/ | grep nolocal) nolocal.jar
       - name: Install Oracle Cloud Infrastructure CLI
-        uses: bytesbay/oci-cli-action@v1.0.2 
+        uses: bytesbay/oci-cli-action@v1.0.2
         with:
           user: ${{secrets.OCI_USER_OCID}}
           fingerprint: ${{secrets.OCI_FINGERPRINT}}
@@ -45,9 +47,8 @@ jobs:
           region: ${{secrets.OCI_REGION}}
           api_key: ${{secrets.OCI_KEY_FILE}}
       - name: Set up ssh keys
-        run: | 
-          echo "${{secrets.VM_SSH_PUB_KEY}}" > /home/runner/.oci/id_vm.pub
-          echo "${{secrets.VM_SSH_PRIVATE_KEY}}" > /home/runner/.oci/id_vm.key
+        run: |
+          echo "${{secrets.VM_SSH_PUB_KEY}}" >> /home/runner/.oci/id_vm.pub
       - name: Check existing instance
         run: |
             echo "INSTANCE_OCID=$( \
@@ -75,3 +76,42 @@ jobs:
               --query "data.id" \
               --raw-output \
           )" >> $GITHUB_ENV
+      - name: Get Instance IP
+        run: |
+          echo "INSTANCE_IP=$( \
+            oci compute instance list-vnics \
+            --instance-id ${{env.INSTANCE_OCID}} \
+            --query 'data [0]."public-ip"' \
+            --raw-output \
+          )" >> $GITHUB_ENV
+      - name: SSH wait
+        run: |
+          while ! nc -w5 -z ${{ env.INSTANCE_IP }} 22; do
+                  sleep 5
+                  echo "SSH not available, retrying..."
+          done; echo "SSH ready!"
+      #no blue green deployment... we are here for the KILL
+      - name: Stop App
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{ env.INSTANCE_IP }}
+          username: ubuntu
+          key: ${{secrets.VM_SSH_PRIVATE_KEY}}
+          script: |
+            pid=`ps aux | grep "nolocal" | grep -v "grep" | awk '{print $2}'`
+            if [ "$pid" == "" ]; then
+              echo "Process not found"
+            else
+              kill -9 $pid
+            fi
+            sudo mkdir -p /app
+            sudo apt install openjdk-11-jre-headless -y
+      - name: Push JAR
+        uses: appleboy/scp-action@master
+        with:
+          host: ${{ env.INSTANCE_IP }}
+          username: ubuntu
+          key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
+          source: "nolocal.jar"
+          target: "app"
+          strip_components: 2
